### PR TITLE
Greeting Application

### PR DESCRIPTION
**Pull request by kennedyowusu**
#Highlights

- [ ] Created a new Rails app called 'hello-rails-react'.
- [ ] Installed needed node dependencies as described in the previous lesson's tutorial.
- [ ] Made sure that the project has a Postgres database set up.
- [ ] Created a table for storing your messages and create 5 different greetings.
- [ ] Created an API endpoint that selects a random greeting from your table
- [ ] Created a static view that will be the root of your app.
- [ ] Created the App component with react-router and render it in static view.
- [ ] Created the Greeting component that will display a greeting. Set it up as a route in your App component.
- [ ] Create a store, an action, and a reducer that will connect to the API endpoint to get the random greeting.
- [ ] Display the random greeting in your Greeting component.

**Below is an image of the running application:**

screenshot

another-one
shot-of-the-app

### CODE REVIEW

**Comment by arslanbisharat** [comment]
Hi @kennedyowusu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect Gitflow. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by addod19** [comment]
### Hi @kennedyowusu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because you did not follow the correct Gut-flow workflow. Git-flow is creating the PR from a descriptive branch name like `webpack-setup` branch into the `develop` branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by kennedyowusu** [comment]
It is interesting how you @addod19 have rejected my project when it clearly follows the GitHub flow. Thank you @addod19

**Comment by addod19** [comment]
> It is interesting how you @addod19 have rejected my project for the second time when it clearly follows the GitHub flow. Thank you @addod19
> 
> when I am sending a PR from dev to main.

@kennedyowusu, why is it interesting? The requirements clearly says we should follow `Git-flow` and not `GitHub-flow` as you have said. Kindly follow the requirements as mentioned by me and the previous code reviewer, we follow given guidelines

**Review by t-yanick — COMMENTED** [review]
# STATUS: INVALID SUBMISSION

Hi @kennedyowusu , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because you did not follow the correct Gut-flow workflow. Git-flow is creating the PR from a descriptive branch name like webpack-setup branch into the develop branch
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
